### ISSUE TITLE
Feedback on Part 1 Learning Design plan

### ISSUE THREAD

**Issue by bronAh** [eallenOP/ldttc#2]
Elise Part 1 is fabulous and definitely in the A grade category. The overarching problem that provided the stimulus for the learning strategy is clearly articulated and the all the pieces fit together, In particular, the 'ducks' line up - Aim, objectives and deliverables. 

- Since the timeline is requested in Part 3, dates are not needed in Part 1. 

The introduction, background and context is **perceptive and thoroughly differentiate**s key factors (tertiary context re IT, stakeholders, cultural factors) is explained clearly and communicated. I really like the use of personas in the learner analysis section as these illustrate typical students and the diversity therein.  Information about the stakeholders is detailed and perceptive. The educational reason for the plan is clear and insightful, and well articulated (according to the first part of the rubric).

Evidence from the literature is used appropriately to support the plan. 

- One question: when you say "...., but, as per recent trends in wider tertiary education, the mode of delivery needs to shift from highly theoretical to being much more practical and experiential. " 
Do you have a reference for this?
I am impressed and would not want you to trim the detail in this part. 
Bronwyn

**Comment by eallenOP** [comment]
Feedback incorporated over a number of new commits.
